# Generated by Django 3.1.2 on 2022-12-02 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
